fix: bug with fetching DSIS data from native
equinor/recall-dsis-client pull request #27
Opened 2023-01-24 08:55 UTC by KristianKjerstad

2023-01-25 08:18 UTC, tassab requested changes
Nice implementation using the odata.nextLink and much faster than before with the select query parameter. 👍

Requests are repeated quite often due to empty response. Might waiting a few ms help? 🤷 Still much faster than before so not really an issue...

Order of attributes in CSV file has to be fixed. See comment.

2023-01-31 10:23 UTC, KristianKjerstad commented on src/use_cases/logs.py
> +        logs.to_csv(file, mode='a', index=False, header=False)
good catch!

2023-02-06 13:48 UTC, tassab approved these changes
Works fine now. I guess, the order of the columns isn't relevant?

2023-02-07 08:23 UTC, KristianKjerstad commented
> Works fine now. I guess, the order of the columns isn't relevant?

I didn't give it much thought, but the order of the columns should probably be in the same order as the old training data so that we can expand the dataset without any issues.

Will create a fix for this!

2023-02-07 10:24 UTC, eoaksnes approved these changes
Nice

2023-02-07 10:28 UTC, tassab approved these changes
👍

2023-02-07 13:22 UTC, merged